/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.TASEC.Proveedor.logic.api;

import co.edu.uniandes.csw.TASEC.Proveedor.logic.dto.ProveedorDTO;
import co.edu.uniandes.csw.TASEC.Proveedor.logic.dto.ProveedorPageDTO;
import java.util.List;

public interface IProveedorLogic {

    public ProveedorDTO createProveedor(ProveedorDTO detail);

    public List<ProveedorDTO> getProveedores();

    public ProveedorPageDTO getProveedores(Integer page, Integer maxRecords);

    public ProveedorDTO getProveedor(Long id);

    public void deleteProveedor(Long id);

    public void updateProveedor(ProveedorDTO detail);
    
    public void agregarServicioCatalogo(ProveedorDTO detail );
}
