/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package co.edu.uniandes.csw.TASEC.ServicioSimple.logic.ejb;

import co.edu.uniandes.csw.TASEC.ServicioSimple.logic.api.IServicioSimpleLogic;
import co.edu.uniandes.csw.TASEC.ServicioSimple.logic.converter.ServicioSimpleConverter;
import co.edu.uniandes.csw.TASEC.ServicioSimple.logic.dto.ServicioSimpleDTO;
import co.edu.uniandes.csw.TASEC.ServicioSimple.logic.dto.ServicioSimplePageDTO;
import co.edu.uniandes.csw.TASEC.ServicioSimple.logic.entity.ServicioSimpleEntity;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;


import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

@Default
@Stateless
@LocalBean
public class ServicioSimpleLogic implements IServicioSimpleLogic {

    @PersistenceContext(unitName = "TasecClassPU")
    protected EntityManager entityManager;

    public ServicioSimpleDTO createServicioSimple(ServicioSimpleDTO servicio) {
        ServicioSimpleEntity entity = ServicioSimpleConverter.persistenceDTO2Entity(servicio);
        entityManager.persist(entity);
        return ServicioSimpleConverter.entity2PersistenceDTO(entity);
    }

    public List<ServicioSimpleDTO> getServiciosSimples() {
        Query q = entityManager.createQuery("select u from ServicioSimpleEntity u");
        return ServicioSimpleConverter.entity2PersistenceDTOList(q.getResultList());
    }

    public ServicioSimplePageDTO getServiciosSimples(Integer page, Integer maxRecords) {
        Query count = entityManager.createQuery("select count(u) from ServicioSimpleEntity u");
        Long regCount = 0L;
        regCount = Long.parseLong(count.getSingleResult().toString());
        Query q = entityManager.createQuery("select u from ServicioSimpleEntity u");
        if (page != null && maxRecords != null) {
            q.setFirstResult((page - 1) * maxRecords);
            q.setMaxResults(maxRecords);
        }
        ServicioSimplePageDTO response = new ServicioSimplePageDTO();
        response.setTotalRecords(regCount);
        response.setRecords(ServicioSimpleConverter.entity2PersistenceDTOList(q.getResultList()));
        return response;
    }

    public ServicioSimpleDTO getServicioSimple(Long id) {
        return ServicioSimpleConverter.entity2PersistenceDTO(entityManager.find(ServicioSimpleEntity.class, id));
    }

    public void deleteServicioSimple(Long id) {
        ServicioSimpleEntity entity = entityManager.find(ServicioSimpleEntity.class, id);
        entityManager.remove(entity);
    }

    public void updateServicioSimple(ServicioSimpleDTO servicio) {
        ServicioSimpleEntity entity = entityManager.merge(ServicioSimpleConverter.persistenceDTO2Entity(servicio));
        ServicioSimpleConverter.entity2PersistenceDTO(entity);
    }
}
